RIPE-NCC/ripe-atlas-tools

ripe/atlas/tools/renderers/aggregate_ping.py
ripe/atlas/tools/renderers/templates/reports/aggregate_ping.txt

It still needs more love (better formatting, testing...), but at least it works with msm#1001:
```
$ ripe-atlas report --renderer aggregate_ping 1001
RIPE Atlas Report for Measurement #1001
===================================================
Collecting results...
-- 193.0.14.129 ping statistics ---
26711 packets transmitted, 26350 received, 1.35150312605% loss
rtt min/med/avg/max = 0.209/33.274/60.5296812673/14027.879 ms
```
We'll rebase all the commits in this PR before merging.
Also, how about adding this to the standard ping renderer?

Extend aggregate_ping renderer

---

ripe/atlas/tools/commands/probes.py
ripe/atlas/tools/probes/__init__.py
ripe/atlas/tools/renderers/probes.py
tests/commands/probes.py

Looking for code review on this one.  Much of what I've changed is just PyCharm's linter complaining, and a few typos, but specifically, there's one spot where I've changed the use of pipes to spaces in the probe output to be more like other common unix command line tools (`df`, `ls`, etc.)

Replaced pipes with spaces

---

ripe/atlas/tools/renderers/base.py

So, after writing some tests for report I found out that the following code breaks if type is something we don't have.
```python
self.renderer = Renderer.get_renderer(
self.arguments.renderer, detail["type"]["name"])()
```
In general it's fine to break but not with Import error exception. It's better if we raise the RipeAtlasToolsException with a descriptive message. So that's what tis PR is handling.

make sure import renderer explodes only with RipeAtlasToolsException

---

ripe/atlas/tools/commands/measure.py
ripe/atlas/tools/settings/__init__.py
scripts/ripe-atlas
tests/__init__.py
tests/base.py
tests/commands/__init__.py
tests/commands/measure.py
tests/commands/measurements.py

The tests here cover all methods of the `measure` command except for `run()`, `create()`, and `stream()`.  I'm also including a bunch of fixes that I found I had to do once I got the tests running.

Test coverage for the <measure> command

---

tests/__init__.py

This will cause a tests failure, since it looks like the `report` tests are a little broken, but this PR fixes the bug that caused us to miss this in the first place ;-)

Add report, measure, and measurements to the complete list of tests

---

scripts/ripe-atlas

Given that we're not using 2.6 anymore, there's no reason to use that nasty syntax for dynamic imports.  Importlib is already being used in the renderer import code, so I just updated this section too.

Using importlib is a lot cleaner

---

ripe/atlas/tools/commands/report.py
ripe/atlas/tools/helpers/rendering.py
ripe/atlas/tools/renderers/base.py
ripe/atlas/tools/renderers/dst_asn.py
ripe/atlas/tools/renderers/raw.py
tests/__init__.py
tests/renderers/__init__.py
tests/renderers/raw.py

This way we allow users write their own renderers and not use our own default header/footer if they want. I added also couple of tests for raw renderer, since I as there.

allow custom renderers to discard default header/footer

---

ripe/atlas/tools/renderers/traceroute.py

#105 points out a case where Python3 didn't like using `.format()` and `None` together, but while figuring this out, I realised that we weren't even accounting for cases where the `hop` had an error, so I patched that too (with colours!)
In addition to that, I've made one edit that I checked with the local nerds here: I've introduced tabulation in the output so now we have neat columns and `*` instead of a roughly unformatted use of `None` etc.

Fixes for Python3.4 explosions with None

---

ripe/atlas/tools/commands/measure/base.py
tests/commands/measure.py

Does what it says on the tin.  I had to do a little hacking there due to how argparse handles mutually exclusive arguments (you can't have overlapping groups of such arguments), but the code is reasonably simple and easy-to-follow.
Closes #98.

Smarter handling of --probes and --from-probes

---

ripe/atlas/tools/cache.py

I couldn't find a simpler way to get the full python version.  `sys.version_info` seems to only have the version component data and not stringified version.  `sys.version` is just a Very Long String, so this seemed like the best option.
Closes #106.

Set the cache file name to include the python version

---

ripe/atlas/tools/commands/base.py
ripe/atlas/tools/commands/measurement.py
ripe/atlas/tools/commands/probe.py

After a discussion with @robert-kisteleki in #103, I figured that adding these wouldn't be too much effort and it wasn't, so I've added them here.
Basically it's a means for you to get all the details about a measurement or probe on the command line:
$ ripe-atlas measurement 1000192
ID                         1000192
URL                        https://atlas.ripe.net/measurements/1000192/
Type                       Ping
Status                     Ongoing
Description                -
Address Family             4
Public?                    ✔
One-off?                   ✘
Destination Name           hsi.cablecom.ch
Destination Address        62.2.16.12
Destination ASN            6830
Interval                   360
Spread                     -
Created                    2012-01-31 15:19:49 UTC …

New metadata "detail" commands

---

setup.py

It turns out that we don't need to be so picky about our dateutil version, so for the sake of the FreeBSD port, I've removed that bit here.  I've also bumped the Sagan dependency to keep things in sync.

Remove dateutil version and bump sagan

---

CHANGES.rst
ripe/atlas/tools/commands/report.py
tests/commands/report.py
tests/renderers/ssl_consistency.py

Closes #103
Removing the header because as @robert-kisteleki points out, it's largely useless.  If the user wants metadata about the measurement, she can invoke `ripe-atlas measurement <id>`.

Remove header from report

---

tox.ini

We had a py3 syntax error on dst_asn.py on previous versions that apparently wasn't caught with existing checks. That do the job now.

Adding additional tox test 

---

ripe/atlas/tools/renderers/http.py
ripe/atlas/tools/renderers/ntp.py
tests/__init__.py
tests/renderers/__init__.py
tests/renderers/http.py

We didn't have a renderer for HTTP, so I borrowed one from the W3C.
Closes #119

Using the extended log file format for HTTP

---

CHANGES.rst
docs/index.rst
docs/plugins.rst
ripe/atlas/tools/helpers/rendering.py
ripe/atlas/tools/renderers/aggregate_ping.py
ripe/atlas/tools/renderers/base.py
ripe/atlas/tools/renderers/dst_asn.py
ripe/atlas/tools/renderers/http.py
ripe/atlas/tools/renderers/ntp.py
ripe/atlas/tools/renderers/ping.py
ripe/atlas/tools/renderers/ssl_consistency.py
ripe/atlas/tools/renderers/templates/reports/aggregate_ping.txt
ripe/atlas/tools/renderers/traceroute.py
ripe/atlas/tools/renderers/traceroute_aspath.py
ripe/atlas/tools/version.py
tests/renderers/aggregate_ping.py
tests/renderers/http.py
tests/renderers/ping.py
tests/renderers/ssl_consistency.py

I started just writing the doc, but when I tried to follow along in the plugin creation process, I ran into a lot of inconsistencies in how we implement the renderer logic:
* `header()`, `additional()` and `footer()` weren't printed, but rather relied on the user to execute a print within them, while on_result() returned data to be printed.
* Each renderer's `on_result()` method was expected to return a `Result` object, which was just the string + the probe id.  This was just as easily accomplished in the `Rendering` class, so I moved this logic up into that, leaving the on_result() to just return a plain old string.
* I defined \__init__() as an empty method that expects `*args` and `**kwargs` and changed both the documentation and all of the existing renderers to invoke the parent. …

Added howto for plugins and updated the rendering framework for consistency

---

ripe/atlas/tools/commands/measure/dns.py
ripe/atlas/tools/commands/measure/traceroute.py
tests/commands/measure.py

While testing the command line tools, found a little bit pedantic to reject parameters just because they are in lower case. This applies for DNS measurements with 'protocol', 'query-class' and 'query-type', as well as Traceroute measurements with 'protocol'.
Made the tweaks to accept lower, upper or mixed case, and corresponding test cases. All tests pass.

DNS and Traceroute measurements can accept parameters in lower case 

---

ripe/atlas/tools/cache.py
ripe/atlas/tools/commands/base.py
ripe/atlas/tools/exceptions.py
ripe/atlas/tools/helpers/colours.py
ripe/atlas/tools/renderers/traceroute.py
ripe/atlas/tools/settings/__init__.py
scripts/ripe-atlas

OK, let's try this again (replacing https://github.com/RIPE-NCC/ripe-atlas-tools/pull/148).
This request makes some small fixes to add Windows support.
There is also a small change moving the get_available_commands function from scripts/ripe-atlas to ripe/atlas/tools/commands/base.py. This is comparable to what already happens with ripe/atlas/tools/renderers/base.py, and allows me to override this function with pyinstaller (because scripts/ripe-atlas can't be imported from anywhere).

Fixes needed for Windows support

---

ripe/atlas/tools/commands/measurements.py
tests/commands/measurements.py

That's an easy fix for the default output. We were not counting spaces inbetween fields. Decreasing descr a bit it fixes the issue. If we need to do it for every custom output probably it's going to be a bit harder but we can see it later upon user's request.

Make sure we have 80width for default output

---

scripts/ripe-atlas

"No such command" was frequently hiding various dependency and other import issues. This change checks that the ImportError actually concerns the relevant command module.

Only raise the 'No such command' exception if it's the actual command module that isn't found

---

ripe/atlas/tools/commands/base.py
ripe/atlas/tools/commands/configure.py
ripe/atlas/tools/commands/measure/__init__.py
ripe/atlas/tools/commands/measurement_info.py
ripe/atlas/tools/commands/measurement_search.py
ripe/atlas/tools/commands/probe_info.py
ripe/atlas/tools/commands/probe_search.py
ripe/atlas/tools/commands/render.py
ripe/atlas/tools/commands/report.py
ripe/atlas/tools/commands/stream.py
scripts/ripe-atlas
tests/__init__.py
tests/commands/__init__.py
tests/commands/loading.py
tests/commands/measurement_search.py
tests/commands/probe_search.py

Summary of changes:
1. Renamed some commands
2. Made the help text more informative and consistent
3. Refactored the command import code
We found that users were confused by similar-looking commands like measure/measurement/measurements and probe/probes. This change makes the following renames, preserving backwards compatibility using deprecated aliases:
- measurement -> measurement-info
- measurements -> measurement-search
- probe -> probe-info
- probes -> probe-search
I made the help text more consistent in tense, and a few other tweaks. I also changed to provide a short description of the commands when you run "ripe-atlas --help", and a list of measurement types when you run "ripe-atlas measure --help".
I have also refactored some of the import code so that
1. we can support dashes in …

Rename some commands

---

ripe-atlas-bash-completion.sh
ripe/atlas/tools/commands/measure/__init__.py
scripts/ripe-atlas
tests/test_bash_completion.py

This is highly inspired from how Django is doing auto-completion. It
uses bash's complete build in function to get the available options
there are for each input. The main idea is that now we have a function
that can intervene the normal execution of ripe-atlas script and can
return back available options in a format compatible with what
bash's complete function expects. This function will intervene
only if we have an enviromental variable set, which is what
ripe-atlas-bash-completion.sh is taking care of. I had to do
changes in ripe-atlas script to make sure I can get all available
options any time without getting to the execution logic of any command
and also make sure ripe-atlas script won't return before autocomplete
function has run.

Fixes partially #113, as it adds auto-completion for bash shell

---

ripe/atlas/tools/commands/probe_search.py

When invoking the tool with `probe-search` command and `--all` option, `--limit` is set to None. This causes Python 3.x to throw an exception in the print statement that attempts to show the number of probes retrieved; the exception is the result of passing a `NoneType` to a `min` function. The code works in Python 2.x since `min(None, ...)` returns None. The commit also includes a minor fix to handle the case when 'geometry' attribute is not available for a probe.

Minor issues when running on Python 3.5.1

---

ripe/atlas/tools/cache.py
ripe/atlas/tools/commands/measure/base.py
ripe/atlas/tools/commands/report.py
ripe/atlas/tools/commands/stream.py
ripe/atlas/tools/ipdetails.py
ripe/atlas/tools/renderers/base.py
ripe/atlas/tools/renderers/traceroute_aspath.py
ripe/atlas/tools/streaming.py
tests/commands/report.py
tests/renderers/traceroute_aspath.py
tests/test_ipdetails.py

In order to allow Renderers to add their own custom arguments to the main `argparse` and to receive optional user-provided parameters I've introduced a new method, `add_arguments()`. Everywhere the `--renderer` argument is provided the `Renderer.add_arguments_for_available_renderers()` method is called too: it cycles through all the `Renderer` classes and calls their `add_arguments()` method.
When the renderer is instantiated its `__init__()` is provided with the full `argparse.parse_args()` results, so that it can read its own optional arguments.
This new internal feature can be used to fix #155 for example (see the `--traceroute-aspath-radius` argument).

A method to pass options to renderers

---

ripe/atlas/tools/commands/alias.py
ripe/atlas/tools/commands/base.py
ripe/atlas/tools/commands/configure.py
ripe/atlas/tools/commands/go.py
ripe/atlas/tools/commands/measure/base.py
ripe/atlas/tools/commands/measurement_info.py
ripe/atlas/tools/commands/probe_info.py
ripe/atlas/tools/commands/report.py
ripe/atlas/tools/commands/stream.py
ripe/atlas/tools/helpers/validators.py
ripe/atlas/tools/settings/__init__.py
tests/commands/alias.py
tests/commands/loading.py
tests/commands/measure.py
tests/commands/report.py
tests/helpers/validators.py

I really like @danielquinn's idea (#172)!
I came up with this PR that uses the same approach already seen on #138 (API keys aliases).
It allows to add an alias while creating a new measurement:
```
$ ripe-atlas measure ping --target 8.8.8.8 --set-alias ping_google
```
Or to configure an alias for an existing one:
```
$ ripe-atlas configure --set "measurement.alias.traceroute_ripe=1674977"
```
Finally, commands can be run by passing a measurement ID or alias:
```
$ ripe-atlas report ping_google
$ ripe-atlas go traceroute_ripe
```
This is what I quickly got by tweaking the existing code without introducing/modifying core functionalities.
My solution is based on the user local configuration (`~/.config/ripe-atlas-tools/rc`), and that may be a limit (I'm thinking about teams which share the …

Measurement aliases (#172)

---

ripe/atlas/tools/commands/stream.py

The "stream" command was inadvertently passing a string representation of a Python function as the "?key=" parameter to the measurements API. This used to be silently ignored by the API, but it was recently changed to explicitly reject malformed or non-existent keys.
Providing a "fetch" key is actually not necessary anyway in this case, because the stream service doesn't support non-public measurements so if we can't fetch the metadata then we may as well give up.

Fixed broken key in stream command by removing the key

---

ripe/atlas/tools/helpers/colours.py

The colourisation previously used a run-off-the-mill string for interpolation. This caused problems in Python 2.x if unicode data was to be colourized. This PR fixes that.
Cheers

Use unicode literal in colourisation

---

ripe/atlas/tools/cache.py

Checking with "not" seems not to work even when the cache is already initialized, causing a retry on open which is presumably not allowed by gdbm.
Fixes #177.

Fix cache open

---

ripe/atlas/tools/renderers/ntp.py

This commit adds a simple renderer for NTP responses, even when not completely thought it is probably better than nothing :-)
Example output:
```
Probe #28460
===============================================================================
[NTP] 134.169.5.13 -> 129.250.35.250 (129.250.35.250)
version: 4, stratum: 2/16
refid: f9e063d5
leap: no, poll: 1, precision: 9.537e-07
root_delay: 0, root_disp: 0.00260925
ref-time: 2087-03-13 11:04:27.139235
[0] 0.016|-0.287309
trans: 2017-03-13 10:16:39.361360+00:00 -> recv: 2017-03-13 10:16:39.361338+00:00
origin: 2017-03-13 10:16:39.066158+00:00 -> final: 2017-03-13 10:16:39.081922+00:00
[1] 0.016|-0.28729699999999997
trans: 2017-03-13 10:16:39.377500+00:00 -> recv: 2017-03-13 10:16:39.377489+00:00
origin: 2017-03-13 10:16:39.082377+00:00 -> final: …
```

Add a simple NTP renderer

---

ripe/atlas/tools/renderers/dns_compact.py
tests/renderers/__init__.py
tests/renderers/dns_compact.py

The renderer named dns_compact displays just the most important parts of
a DNS results: probe id, date and time, status code, flags and records
from ANSWER section of the DNS message. Each result is printed on one
line.
Signed-off-by: Ondřej Caletka <ondrej@caletka.cz>

Add compact DNS results renderer

---

ripe/atlas/tools/commands/measure/traceroute.py
tests/commands/measure.py

"ripe-atlas measure traceroute" imposes a minumum of size "1" to packets, but this won't allow "tcp ping" as documented in https://labs.ripe.net/Members/wilhelm/measuring-your-web-server-reachability-with-tcp-ping
I modified the minimum value to 0, adjusted the tests directory, and successfully create a tcp-ping measurement: https://atlas.ripe.net/measurements/9717581/#!general
using:
ripe-atlas measure traceroute --protocol TCP --size 0 --first-hop 64 --max-hops 64 --from-country CL --probes 10 --target www.nic.cl

Allow "tcp ping" for traceroute measurements

---

ripe/atlas/tools/commands/base.py
ripe/atlas/tools/commands/measurement_search.py
ripe/atlas/tools/commands/probe_info.py
ripe/atlas/tools/commands/probe_search.py
ripe/atlas/tools/helpers/colours.py
tests/commands/measurement_search.py
tests/commands/probe_search.py

PR #179 caused some mixing of unicode and strings. Commands like "ripe-atlas measurement-info 5001" start breaking. This commit tries to make they way we treat prints and output to file safer. That means we try to use unicode everywhere and as soon as we print we transform to byte strings with utf8 encoding. This way outputing to file is safe (it used to break before).
To be honest the best and cleanest would be to use a custom wrapper for print and make all logs byte strings before printing. This way printing to shell and redirecting to file would be safe.
For now it seems to fix the issues we had but if we discover more we should go for the general solution.

Unicode problems

---

dev-scripts/compare-openapi-spec.py
ripe/atlas/tools/commands/measure/base.py
ripe/atlas/tools/commands/measure/dns.py
ripe/atlas/tools/commands/measure/http.py
ripe/atlas/tools/commands/measure/ntp.py
ripe/atlas/tools/commands/measure/ping.py
ripe/atlas/tools/commands/measure/sslcert.py
ripe/atlas/tools/commands/measure/traceroute.py
ripe/atlas/tools/settings/__init__.py
tests/commands/loading.py
tests/commands/measure.py

Synchronize option, limits and defaults with the API where relevant,and include a new dev script for checking the tools against the OpenAPI endpoint.
This means adding a few more options that are supported by the API but not the tools, and aligning the minimums and maximums with current reality. In general the behaviour of the CLI has not changed, except that server-side validation errors are less likely and certain values are now possible.

Synchronize option, limits and defaults with the API

---

ripe/atlas/tools/renderers/ntp.py
ripe/atlas/tools/renderers/sslcert.py
ripe/atlas/tools/renderers/traceroute.py

When analyzing for example traceroute reports, it is crucial to know when was the result obtained.  This PR adds result date to the output of traceroute, SSL and NTP renderers.
I also simplified the NTP renderer, dropping unused variables/parameters.
All tests pass.

Add result date and time to traceroute, NTP and SSL renderers

---

docs/use.rst
ripe/atlas/tools/commands/measure/base.py

Hi
I thought it would be nice to have an option to open browser immediately when doing measurements.
I know there is a go option, but then you need to know the id, which is created when you do the measurement.
how to use:
ripe-atlas measure traceroute --target www.nordu.net --go-web

Adding option to open measurement URL in browser

---

ripe/atlas/tools/commands/measure/base.py

Working in the RIPE NCC Hackathon in Dublin we are trying to make the initial experience using the tools better. One thing is that a lot of people will be missing an API key so they will get the 403 status code. So this is just a small helping text guiding the user a bit.

Trying to make the initial experience better, if 403 errors

---

.travis.yml
ripe/atlas/tools/cache.py
ripe/atlas/tools/commands/base.py
ripe/atlas/tools/helpers/colours.py
ripe/atlas/tools/helpers/sanitisers.py
ripe/atlas/tools/helpers/xdg.py
ripe/atlas/tools/renderers/base.py
ripe/atlas/tools/settings/__init__.py
setup.py
tox.ini

`ripe-atlas` currently half-implements the XDG Base Directory Specification. This commit fixes the support to look for `XDG_CONFIG_HOME` first, as it ought to.
(This PR fixes #204, which had a typo, and thus was broken.)
Unfortunately, this PR also contains a bunch of changes to make the build system happy as the test suite has been broken for quite a while.
I should note that I also had to peg the version of mock at 3.0.5 as this is the last version that supports Python 2.7.

Proper XDG Base Directory Specification support

---

ripe/atlas/tools/renderers/ssl_consistency.py
tests/renderers/ssl_consistency.py

When a mesurement has no cert data because all of the probes failed, an exception
is thrown in the ssl consistency renderer. This max() call needs to be guarded with
a check.
```
Traceback (most recent call last):
File "/Users/tomarnfeld/src/github.com/ripe-ncc/ripe-atlas-tools.git/tests/renderers/ssl_consistency.py", line 202, in test_get_nprobes_ofpopular_cert_empty
self.assertEquals(renderer.get_nprobes_ofpopular_cert(), 0)
File "/Users/tomarnfeld/src/github.com/ripe-ncc/ripe-atlas-tools.git/ripe/atlas/tools/renderers/ssl_consistency.py", line 68, in get_nprobes_ofpopular_cert
[self.uniqcerts[cert_id]["cnt"] for cert_id in self.uniqcerts]
ValueError: max() arg is an empty sequence
```
I replicated this by running a simple probe measurement, for example.
```
$ ripe-atlas measure sslcert …
```

SSL consistency renderer cannot call max() with no arguments

---

ripe/atlas/tools/commands/probe_search.py
ripe/atlas/tools/settings/__init__.py

Google has changed the Geocoding API conditions, now every request has
to be authenticated with an API key of an account connected to a billing
account. Thus I added an option to provide such API key on command line
as well as in the config file.
I also fixed the error reporting so any Google API errors are presented
to the user.
Signed-off-by: Ondřej Caletka <ondrej@caletka.cz>

Fix --location probe search

---

ripe/atlas/tools/commands/measure/base.py
ripe/atlas/tools/commands/report.py

This pull request adds possibility to pass create and fetch API keys with `ATLAS_CREATE_KEY` and `ATLAS_FETCH_KEY` environment variables.

Add possibility to pass API keys using env variables

---

ripe/atlas/tools/commands/measure/dns.py
ripe/atlas/tools/settings/__init__.py

This is a contribution from the Shadow Hunters hackathon team during the AIS2019
In the course of our hackathon challenge we scheduled DNS over TLS measurements from probes in Africa to cloud resolvers to compare their RTT and responsiveness to local resolvers.
To our surprise we even found 14 local DNS-over-TLS configured on probes in Africa.

Add --tls option to schedule DNS requests over TLS

---

docs/installation.rst

The OpenBSD package name of ripe-atlas-tools changed from py-ripe.atlas.tools to ripe.atlas.tools from OpenBSD 6.1
http://cvsweb.openbsd.org/cgi-bin/cvsweb/ports/net/py-ripe.atlas.tools/pkg/PLIST
I confirmed the instruction using "pkg_add ripe.atlas.tools" at OpenBSD 6.4

Remove the py prefix from OpenBSD PKGNAME

---

MANIFEST.in

This enables packaging with a user-agent file, useful for downstream packagers.

feat: support building sdist/wheels with UA

---

ripe/atlas/tools/commands/probe_search.py

Increasing of characters width for the field "ID". It was fixed to 5, but currently the ID of the probes is up to 7 ciphers (characters).

Correct error in size of field ID in probe_search.py 
