RIPE-NCC/ripe-atlas-tools

ripe/atlas/tools/commands/probes.py, ripe/atlas/tools/renderers/probes.py
Changing print format of ids-only after @pierky suggestion.
=> change format of ids-only to comma seperated ids

ripe/atlas/tools/commands/report.py
If I'm right the `on_finish` method of renderer was no more considered. I added it after aggregation output.
=> renderer.on_finish output after aggregation

ripe/atlas/tools/aggregators/base.py
Mostly just bringing everything under 80 characters, with one exception, I rejigged one method to not need the `for...else` construct since you were delcaring `buckets=None` there by default.
=> Conformed all the things

ripe/atlas/tools/commands/configure.py, ripe/atlas/tools/commands/measure.py, ripe/atlas/tools/settings/__init__.py
Fix for #25 based heavily on work from @pierky.  This is the result of a brief discussion on the issue queue as well as a manual merge against conflicts created in other branches.  It also fixes a bug introduced when Cousteau changed its API wrt one-offs.
I'm hoping to get a :+1: from @pierky on this to show that it's doing what he wanted it to do, and @astrikos I guess you can review & merge it if you see fit.
=> Tags Support

ripe/atlas/tools/commands/report.py, ripe/atlas/tools/helpers/rendering.py, ripe/atlas/tools/renderers/base.py
Fixes #53 
I also added a few docstrings.
=> Make --renderer raw actually be raw

ripe/atlas/tools/commands/render.py
The initial intention of the `render` command was to take in the so-called "fragmented json` files that we typically work with: one JSON result per line, times `n` lines.  However @spakka already did what I didn't expect: he dumped a multiple results as one continuous JSON blob into the renderer.
We *should* be able to handle this, but this comes with the caveat that dumping 100GB of a single JSON string into this parser will undoubtably crash your system.  However, with reasonably-sized blobs, this should work just fine.
Closes #43
=> Allow Great Big JSON Blobs to be passed to the renderer command

.travis.yml, tox.ini
Travis + tox for py27, py34, pypy
=> add continuous integration with travis and tox

docs/installation.rst
I'm just going to merge this one direct.
=> Added note for Python 2.7

ripe/atlas/tools/renderers/aggregate_ping.py, tests/renderers/aggregate_ping.py
@ioc32 this renderer was broken after some changes in base Renderer, so that's a fix to it and I took the time to add some tests on it
=> unbreak aggregate_ping renderer and add tests to it

docs/use.rst
Closes #71 
Just a quick blurb about the shortcuts.
=> Added shortcut docs

ripe/atlas/tools/renderers/dst_asn.py
added a renderer, specific for ping /resolve on probe / multiple destinations
=> new renderer for when dst is in multiple ASNs

CHANGES.rst
Gathering changes that I could find since last release. I might have missed something though.
I used Cousteau's format but we can change it if we think is not appropriate for this.
=> starting changelog for next release

README.rst
I think it's time. Otherwise people will always treat it as beta. There will always be bugs here and there but the coming version is quite stable i think (famous last words :p )
=> remove Disclaimer section

docs/installation.rst
Signed-off-by: Ondřej Caletka <ondrej@caletka.cz>
=> Fix GitHub installation URL

tests/docs.py
Added basic tests for the docs.  Special thanks to [Mariusz Jamro on Stack Overflow](http://stackoverflow.com/questions/33896196/how-to-test-the-validity-of-your-sphinx-documentation).
=> New tests for documentation generation

MANIFEST.in, ripe/atlas/tools/renderers/dst_asn.py
As per the PR in the Cousteau repo, I'm adding the tests here.  I'm also fixing the use of a print statement that should be a print function.
=> Add tests and fix Python3 support

docs/installation.rst, docs/troubleshooting.rst
I ran into these while debugging a ticket from a user, but figure they should make it into the next release.
=> A few documentation additions

CHANGES.rst, ripe/atlas/tools/version.py, setup.py
* Updated the changelog
* Bumped the version numbers for Sagan & Cousteau
* Updated the Magellan version
=> Next release housekeeping

MANIFEST.in, ripe/atlas/tools/version.py, tests/commands/measure.py
The changes to the MANIFEST file mean that the templates aren't included and neither is the YAML file!
=> The latest release 1.2.0 is broken

PACKAGING.md
I've added the link to my github account :)
=> Add github link

ripe/atlas/tools/commands/probes.py, tests/commands/probes.py
The only caveat with this implementation is that you have to explicit pass radius 0 if you need specific lat/lon, but i would guess nobody is doing that anyhow, it doesn't make really sense.
=> default radius is 15 now - fixes #141

CHANGES.rst, ripe/atlas/tools/version.py
This is just a heads up for new release! I am merging and releasing to PYPI soon
=> bump version and create changes for upcoming version

ripe/atlas/tools/renderers/traceroute.py
A new optional argument for `traceroute` renderer, to add AS numbers to traceroutes' output. Tentatively proposing an output format like this:
```
$ ripe-atlas report 1115418 --traceroute-show-asns --probes 6028
Probe #6028
1 94.126.208.17                 AS48294    3.041 ms     1.127 ms     0.918 ms
2 172.16.255.69                            0.989 ms     0.931 ms     1.063 ms
3 94.126.208.1                  AS48294    1.549 ms     0.761 ms     0.428 ms
4 78.33.54.77                    AS8468    0.525 ms      0.41 ms     0.442 ms
5 188.39.127.100                 AS8468    7.155 ms     7.707 ms     7.054 ms
6 188.39.127.68                  AS8468    8.865 ms     8.779 ms     8.815 ms
7 188.39.127.72                  AS8468     7.08 ms     7.208 ms    10.585 ms
8 188.39.11.66 …
```
=> Add --traceroute-show-asns to traceroute renderer

docs/use.rst
Adding the newly exposed flag to docs
=> Add new `--resolve-on-probe` flag to docs

ripe/atlas/tools/commands/base.py, ripe/atlas/tools/commands/measurement_search.py, ripe/atlas/tools/commands/probe_info.py, ripe/atlas/tools/commands/probe_search.py, ripe/atlas/tools/helpers/colours.py, ripe/atlas/tools/helpers/rendering.py, tests/commands/measurement_search.py, tests/commands/probe_search.py
This fixes #207 
Signed-off-by: Ondřej Caletka <ondrej@caletka.cz>
=> Proper fix of unicode rendering in Python 3

docs/installation.rst
This links the unofficial docker image with the tools which I am maintaining.
=> Added link for unofficial docker image
